// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/core/data/models/ldb_group.dart';
import 'src/core/data/models/ldb_item.dart';
import 'src/core/data/models/ldb_location.dart';
import 'src/core/data/models/ldb_move_task.dart';
import 'src/core/data/models/ldb_room.dart';
import 'src/core/data/models/ldb_toss_task.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6853882972704750866),
    name: 'LdbGroup',
    lastPropertyId: const obx_int.IdUid(5, 932579400851393814),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2937731558704870221),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1627106399561563538),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2994436730940823030),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2419288585542955910),
        name: 'imageBytes',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 932579400851393814),
        name: 'subGroupId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 1776741205852147541),
        relationTarget: 'LdbGroup',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1080030442287171865),
    name: 'LdbItem',
    lastPropertyId: const obx_int.IdUid(7, 3502795990010228169),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4453702718778559637),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7088229138213660982),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1159076210894445184),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9088985971940859816),
        name: 'imageBytes',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4008363200067282034),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 729182457716138699),
        name: 'condition',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3502795990010228169),
        name: 'locationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 7592040704796605311),
        relationTarget: 'LdbLocation',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2078028015223251829),
    name: 'LdbLocation',
    lastPropertyId: const obx_int.IdUid(3, 6887709095693850221),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3946750777942251374),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2829017946624001641),
        name: 'roomId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6887709095693850221),
        name: 'groupId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8140131509334363252),
    name: 'LdbMoveTask',
    lastPropertyId: const obx_int.IdUid(3, 131888576371937401),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9017396925867865846),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 949425361189232594),
        name: 'itemId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 9166197447287741527),
        relationTarget: 'LdbItem',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 131888576371937401),
        name: 'destinationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 6087557479809661494),
        relationTarget: 'LdbLocation',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7666764285948910825),
    name: 'LdbRoom',
    lastPropertyId: const obx_int.IdUid(4, 8463476478924965799),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6704368999236519522),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1643975182789207885),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9146700533660021457),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8463476478924965799),
        name: 'imageBytes',
        type: 27,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7880473287807900153),
    name: 'LdbTossTask',
    lastPropertyId: const obx_int.IdUid(2, 1506755906974476800),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7042760143053891643),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1506755906974476800),
        name: 'itemId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 2829190920006502094),
        relationTarget: 'LdbItem',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 7880473287807900153),
    lastIndexId: const obx_int.IdUid(5, 2829190920006502094),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    LdbGroup: obx_int.EntityDefinition<LdbGroup>(
      model: _entities[0],
      toOneRelations: (LdbGroup object) => [object.subGroup],
      toManyRelations: (LdbGroup object) => {},
      getId: (LdbGroup object) => object.id,
      setId: (LdbGroup object, int id) {
        object.id = id;
      },
      objectToFB: (LdbGroup object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final imageBytesOffset = object.imageBytes == null
            ? null
            : fbb.writeListInt64(object.imageBytes!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, imageBytesOffset);
        fbb.addInt64(4, object.subGroup.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final imageBytesParam = const fb.ListReader<int>(
          fb.Int64Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = LdbGroup(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          imageBytes: imageBytesParam,
        );
        object.subGroup.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.subGroup.attach(store);
        return object;
      },
    ),
    LdbItem: obx_int.EntityDefinition<LdbItem>(
      model: _entities[1],
      toOneRelations: (LdbItem object) => [object.location],
      toManyRelations: (LdbItem object) => {},
      getId: (LdbItem object) => object.id,
      setId: (LdbItem object, int id) {
        object.id = id;
      },
      objectToFB: (LdbItem object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final imageBytesOffset = object.imageBytes == null
            ? null
            : fbb.writeListInt64(object.imageBytes!);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, imageBytesOffset);
        fbb.addOffset(4, tagsOffset);
        fbb.addInt32(5, object.condition);
        fbb.addInt64(6, object.location.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final imageBytesParam = const fb.ListReader<int>(
          fb.Int64Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final conditionParam = const fb.Int32Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object = LdbItem(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          imageBytes: imageBytesParam,
          tags: tagsParam,
          condition: conditionParam,
        );
        object.location.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.location.attach(store);
        return object;
      },
    ),
    LdbLocation: obx_int.EntityDefinition<LdbLocation>(
      model: _entities[2],
      toOneRelations: (LdbLocation object) => [],
      toManyRelations: (LdbLocation object) => {},
      getId: (LdbLocation object) => object.id,
      setId: (LdbLocation object, int id) {
        object.id = id;
      },
      objectToFB: (LdbLocation object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.roomId);
        fbb.addInt64(2, object.groupId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final roomIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final groupIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final object = LdbLocation(
          id: idParam,
          roomId: roomIdParam,
          groupId: groupIdParam,
        );

        return object;
      },
    ),
    LdbMoveTask: obx_int.EntityDefinition<LdbMoveTask>(
      model: _entities[3],
      toOneRelations: (LdbMoveTask object) => [object.item, object.destination],
      toManyRelations: (LdbMoveTask object) => {},
      getId: (LdbMoveTask object) => object.id,
      setId: (LdbMoveTask object, int id) {
        object.id = id;
      },
      objectToFB: (LdbMoveTask object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.item.targetId);
        fbb.addInt64(2, object.destination.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = LdbMoveTask(id: idParam);
        object.item.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.item.attach(store);
        object.destination.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.destination.attach(store);
        return object;
      },
    ),
    LdbRoom: obx_int.EntityDefinition<LdbRoom>(
      model: _entities[4],
      toOneRelations: (LdbRoom object) => [],
      toManyRelations: (LdbRoom object) => {},
      getId: (LdbRoom object) => object.id,
      setId: (LdbRoom object, int id) {
        object.id = id;
      },
      objectToFB: (LdbRoom object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final imageBytesOffset = object.imageBytes == null
            ? null
            : fbb.writeListInt64(object.imageBytes!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, imageBytesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final imageBytesParam = const fb.ListReader<int>(
          fb.Int64Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = LdbRoom(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          imageBytes: imageBytesParam,
        );

        return object;
      },
    ),
    LdbTossTask: obx_int.EntityDefinition<LdbTossTask>(
      model: _entities[5],
      toOneRelations: (LdbTossTask object) => [object.item],
      toManyRelations: (LdbTossTask object) => {},
      getId: (LdbTossTask object) => object.id,
      setId: (LdbTossTask object, int id) {
        object.id = id;
      },
      objectToFB: (LdbTossTask object, fb.Builder fbb) {
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.item.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = LdbTossTask(id: idParam);
        object.item.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.item.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LdbGroup] entity fields to define ObjectBox queries.
class LdbGroup_ {
  /// See [LdbGroup.id].
  static final id = obx.QueryIntegerProperty<LdbGroup>(
    _entities[0].properties[0],
  );

  /// See [LdbGroup.name].
  static final name = obx.QueryStringProperty<LdbGroup>(
    _entities[0].properties[1],
  );

  /// See [LdbGroup.description].
  static final description = obx.QueryStringProperty<LdbGroup>(
    _entities[0].properties[2],
  );

  /// See [LdbGroup.imageBytes].
  static final imageBytes = obx.QueryIntegerVectorProperty<LdbGroup>(
    _entities[0].properties[3],
  );

  /// See [LdbGroup.subGroup].
  static final subGroup = obx.QueryRelationToOne<LdbGroup, LdbGroup>(
    _entities[0].properties[4],
  );
}

/// [LdbItem] entity fields to define ObjectBox queries.
class LdbItem_ {
  /// See [LdbItem.id].
  static final id = obx.QueryIntegerProperty<LdbItem>(
    _entities[1].properties[0],
  );

  /// See [LdbItem.name].
  static final name = obx.QueryStringProperty<LdbItem>(
    _entities[1].properties[1],
  );

  /// See [LdbItem.description].
  static final description = obx.QueryStringProperty<LdbItem>(
    _entities[1].properties[2],
  );

  /// See [LdbItem.imageBytes].
  static final imageBytes = obx.QueryIntegerVectorProperty<LdbItem>(
    _entities[1].properties[3],
  );

  /// See [LdbItem.tags].
  static final tags = obx.QueryStringVectorProperty<LdbItem>(
    _entities[1].properties[4],
  );

  /// See [LdbItem.condition].
  static final condition = obx.QueryIntegerProperty<LdbItem>(
    _entities[1].properties[5],
  );

  /// See [LdbItem.location].
  static final location = obx.QueryRelationToOne<LdbItem, LdbLocation>(
    _entities[1].properties[6],
  );
}

/// [LdbLocation] entity fields to define ObjectBox queries.
class LdbLocation_ {
  /// See [LdbLocation.id].
  static final id = obx.QueryIntegerProperty<LdbLocation>(
    _entities[2].properties[0],
  );

  /// See [LdbLocation.roomId].
  static final roomId = obx.QueryIntegerProperty<LdbLocation>(
    _entities[2].properties[1],
  );

  /// See [LdbLocation.groupId].
  static final groupId = obx.QueryIntegerProperty<LdbLocation>(
    _entities[2].properties[2],
  );
}

/// [LdbMoveTask] entity fields to define ObjectBox queries.
class LdbMoveTask_ {
  /// See [LdbMoveTask.id].
  static final id = obx.QueryIntegerProperty<LdbMoveTask>(
    _entities[3].properties[0],
  );

  /// See [LdbMoveTask.item].
  static final item = obx.QueryRelationToOne<LdbMoveTask, LdbItem>(
    _entities[3].properties[1],
  );

  /// See [LdbMoveTask.destination].
  static final destination = obx.QueryRelationToOne<LdbMoveTask, LdbLocation>(
    _entities[3].properties[2],
  );
}

/// [LdbRoom] entity fields to define ObjectBox queries.
class LdbRoom_ {
  /// See [LdbRoom.id].
  static final id = obx.QueryIntegerProperty<LdbRoom>(
    _entities[4].properties[0],
  );

  /// See [LdbRoom.name].
  static final name = obx.QueryStringProperty<LdbRoom>(
    _entities[4].properties[1],
  );

  /// See [LdbRoom.description].
  static final description = obx.QueryStringProperty<LdbRoom>(
    _entities[4].properties[2],
  );

  /// See [LdbRoom.imageBytes].
  static final imageBytes = obx.QueryIntegerVectorProperty<LdbRoom>(
    _entities[4].properties[3],
  );
}

/// [LdbTossTask] entity fields to define ObjectBox queries.
class LdbTossTask_ {
  /// See [LdbTossTask.id].
  static final id = obx.QueryIntegerProperty<LdbTossTask>(
    _entities[5].properties[0],
  );

  /// See [LdbTossTask.item].
  static final item = obx.QueryRelationToOne<LdbTossTask, LdbItem>(
    _entities[5].properties[1],
  );
}
